import * as THREE from '../creek-games-3d/three.module.js';
const $=s=>document.querySelector(s),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,100),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('#game').append(renderer.domElement);scene.background=new THREE.Color('#101521');scene.fog=new THREE.Fog('#101521',35,70);scene.add(new THREE.HemisphereLight('#b8d5ff','#26191b',1.8));const spot=new THREE.SpotLight('#fff',45,55,.65,.35);spot.position.set(0,25,3);spot.castShadow=true;scene.add(spot,spot.target);
const ROSTER=[['Titan Rex','The Colossus','#d32b35','#202733',125,78,92],['Jett Viper','Venom Strike','#36a16a','#111a18',104,96,77],['Nova Queen','Main Event','#8b4fd1','#e2b239',110,90,84],['Brick Mason','The Breaker','#d86928','#252525',122,72,94],['Ace Storm','Skyline','#247dd1','#e7e7e7',102,100,76],['Raven Noir','Dark Crown','#2b263f','#be304d',114,86,87],['Max Voltage','Live Wire','#e4bd26','#21569c',108,94,80],['Ivy Steel','Iron Rose','#b92640','#202020',116,84,89]];const mat=(c,r=.65,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m}),keys={};let player,enemy,playing=false,last=performance.now(),time=180,messageTime=0,pinTimer=0,pinning=false,watchMode=false,pinWinner='player';
createArena();setupPicks();camera.position.set(0,8,15);camera.lookAt(0,1.5,0);requestAnimationFrame(loop);
function createArena(){const floor=new THREE.Mesh(new THREE.PlaneGeometry(50,40),mat('#11151d',1));floor.rotation.x=-Math.PI/2;scene.add(floor);const apron=new THREE.Mesh(new THREE.BoxGeometry(15,1.5,11),mat('#151a24',.65));apron.position.y=.75;scene.add(apron);const ring=new THREE.Mesh(new THREE.BoxGeometry(14,.45,10),mat('#d9dce0',.8));ring.position.y=1.7;ring.receiveShadow=true;scene.add(ring);for(const x of [-7,7])for(const z of [-5,5]){const post=new THREE.Mesh(new THREE.CylinderGeometry(.15,.18,4.2,12),mat('#222831',.28,.8));post.position.set(x,3.4,z);scene.add(post)}for(const y of [2.5,3.25,4])for(const z of [-5,5]){const rope=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,14,10),mat('#d31f2b',.38,.15));rope.rotation.z=Math.PI/2;rope.position.set(0,y,z);scene.add(rope)}for(const y of [2.5,3.25,4])for(const x of [-7,7]){const rope=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,10,10),mat('#d31f2b',.38,.15));rope.rotation.x=Math.PI/2;rope.position.set(x,y,0);scene.add(rope)}for(let i=0;i<220;i++){const fan=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.16,.35,3,6),mat(['#e02c36','#246dba','#eee','#e5bd2f'][i%4],.85)),head=new THREE.Mesh(new THREE.SphereGeometry(.13,7,5),mat(['#d69c72','#8f5d43','#edbd92'][i%3],.9));body.position.y=.42;head.position.y=.84;fan.add(body,head);const side=i%4,a=Math.floor(i/4),row=Math.floor(a/28);if(side<2)fan.position.set(side?-10-row*1.1:10+row*1.1,.2,-14+(a%28));else fan.position.set(-14+(a%28),.2,side===2?-8-row*1.1:8+row*1.1);scene.add(fan)}}
function makeWrestler(data,x){const g=new THREE.Group(),skin=mat(['#d8a077','#8c5b42','#b87958'][Math.abs(x)%3],.78),gear=mat(data[2],.42,.2),boot=mat(data[3],.35,.35),torso=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.82,7,15),skin);torso.scale.set(1.15,1,.8);torso.position.y=1.55;const trunks=new THREE.Mesh(new THREE.BoxGeometry(.82,.52,.58),gear);trunks.position.y=1.05;const head=new THREE.Mesh(new THREE.SphereGeometry(.3,18,14),skin);head.position.y=2.35;const limbs=[];g.add(torso,trunks,head);for(const sx of [-.28,.28]){const leg=new THREE.Group(),l=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.7,5,10),skin),b=new THREE.Mesh(new THREE.BoxGeometry(.3,.28,.45),boot);l.position.y=-.4;b.position.set(0,-.92,.08);leg.position.set(sx,.95,0);leg.add(l,b);g.add(leg);limbs.push(leg)}for(const sx of [-.58,.58]){const arm=new THREE.Group(),a=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.68,5,10),skin);a.position.y=-.4;arm.position.set(sx,1.85,0);arm.add(a);g.add(arm);limbs.push(arm)}g.position.set(x,1.93,0);g.userData={data,name:data[0],health:data[4],maxHealth:data[4],speed:data[5]/14,power:data[6],signature:0,cooldown:0,down:0,blocking:false,limbs};g.traverse(o=>{if(o.isMesh)o.castShadow=true});scene.add(g);return g}
function setupPicks(){const options=ROSTER.map((r,i)=>`<option value="${i}">${r[0]} — ${r[1]}</option>`).join('');$('#playerPick').innerHTML=options;$('#enemyPick').innerHTML=options;$('#enemyPick').value='3'}
function start(watching=false){watchMode=watching;const a=ROSTER[Number($('#playerPick').value)],b=ROSTER[Number($('#enemyPick').value)];player=makeWrestler(a,-3);enemy=makeWrestler(b,3);player.rotation.y=Math.PI/2;enemy.rotation.y=-Math.PI/2;$('#pName').textContent=a[0];$('#eName').textContent=b[0];$('#start').classList.add('hide');$('#buttons').style.display=watching?'none':'flex';playing=true;show(watching?'AI VS AI — WATCH LIVE!':`${a[1]} VS ${b[1]}`)}
function distance(){return Math.abs(player.position.x-enemy.position.x)}
function hit(attacker,target,damage,cost,label){if(!playing||attacker.userData.cooldown>0||attacker.userData.down>0)return;if(distance()>2.1){show('TOO FAR AWAY');return}attacker.userData.cooldown=cost;const blocked=target.userData.blocking,actual=damage*(blocked?.28:1);target.userData.health=Math.max(0,target.userData.health-actual);attacker.userData.signature=Math.min(100,attacker.userData.signature+actual*.9);target.userData.down=damage>20&&!blocked?1.5:target.userData.down;target.position.x+=Math.sign(target.position.x-attacker.position.x)*.35;show(blocked?'BLOCKED!':label);if(target.userData.health<=0){target.userData.down=99;show('KNOCKED DOWN — GO FOR THE PIN!')}}
function grapple(){if(distance()>1.8||player.userData.cooldown>0)return show('MOVE CLOSER TO GRAPPLE');player.userData.cooldown=1.2;enemy.userData.down=1.6;enemy.userData.health=Math.max(0,enemy.userData.health-15);player.userData.signature=Math.min(100,player.userData.signature+18);enemy.rotation.z=Math.PI/2;show('POWER GRAPPLE!')}
function signature(){if(player.userData.signature<100)return show('BUILD SIGNATURE TO 100%');if(distance()>2)return show('MOVE CLOSER');player.userData.signature=0;player.userData.cooldown=1.8;enemy.userData.health=Math.max(0,enemy.userData.health-34);enemy.userData.down=3;enemy.rotation.z=Math.PI/2;show(`${player.userData.data[1].toUpperCase()} SIGNATURE!`)}
function pin(){if(enemy.userData.down<=0||distance()>2.3)return show('RIVAL MUST BE DOWN');pinning=true;pinWinner='player';pinTimer=0;player.position.x=enemy.position.x-.5;show('PIN ATTEMPT!')}
function update(dt,t){if(!playing)return;time=Math.max(0,time-dt);$('#timer').textContent=`${String(Math.floor(time/60)).padStart(2,'0')}:${String(Math.floor(time%60)).padStart(2,'0')}`;if(time<=0)return end(player.userData.health>=enemy.userData.health);for(const w of [player,enemy]){w.userData.cooldown=Math.max(0,w.userData.cooldown-dt);if(w.userData.down>0&&w.userData.down<90){w.userData.down-=dt;if(w.userData.down<=0)w.rotation.z=0}}if(watchMode)updateWatch(dt);else{player.userData.blocking=!!keys.e;if(!pinning&&player.userData.down<=0){const move=(keys.d?1:0)-(keys.a?1:0);player.position.x=Math.max(-6.2,Math.min(6.2,player.position.x+move*player.userData.speed*dt));player.rotation.y=enemy.position.x>player.position.x?Math.PI/2:-Math.PI/2}updateEnemy(dt)}if(pinning){pinTimer+=dt;const count=Math.min(3,Math.floor(pinTimer/.8)+1),target=pinWinner==='player'?enemy:player;$('#count').textContent=count;$('#count').style.opacity=1;if(pinTimer>=2.4)return end(pinWinner==='player');if(target.userData.health>25&&Math.random()<dt*(target.userData.health/35)){pinning=false;$('#count').style.opacity=0;target.userData.down=.5;show('KICK OUT!')}}updateHud();messageTime-=dt;if(messageTime<=0)$('#message').style.opacity=0;animate(t)}
function updateWatch(dt){if(pinning)return;watchAct(player,enemy,'player',dt);watchAct(enemy,player,'enemy',dt)}
function watchAct(attacker,target,side,dt){if(attacker.userData.down>0)return;attacker.userData.blocking=Math.random()<.012;if(target.userData.down>0&&distance()<2.3&&Math.random()<dt*.75){pinning=true;pinWinner=side;pinTimer=0;attacker.position.x=target.position.x+(side==='player'?-.5:.5);show(`${attacker.userData.name.toUpperCase()} COVERS FOR THE PIN!`);return}if(distance()>1.65){attacker.position.x+=Math.sign(target.position.x-attacker.position.x)*attacker.userData.speed*.48*dt;attacker.rotation.y=target.position.x>attacker.position.x?Math.PI/2:-Math.PI/2;return}if(attacker.userData.cooldown<=0){if(attacker.userData.signature>=100){attacker.userData.signature=0;attacker.userData.cooldown=1.7;target.userData.health=Math.max(0,target.userData.health-34);target.userData.down=3;target.rotation.z=Math.PI/2;show(`${attacker.userData.data[1].toUpperCase()} SIGNATURE!`)}else{const roll=Math.random();hit(attacker,target,roll>.82?23:roll>.48?14:8,roll>.82?1.35:roll>.48?.8:.48,roll>.82?'POWER SLAM!':roll>.48?'BIG KICK!':'FAST STRIKE!')}}}
function updateEnemy(dt){if(pinning||enemy.userData.down>0)return;enemy.userData.blocking=Math.random()<.012;if(distance()>1.65)enemy.position.x+=Math.sign(player.position.x-enemy.position.x)*enemy.userData.speed*.58*dt;else if(enemy.userData.cooldown<=0){if(player.userData.down>0&&Math.random()<.3){show('RIVAL PIN ATTEMPT!');return end(false)}const roll=Math.random();hit(enemy,player,roll>.78?22:roll>.4?13:8,roll>.78?1.3:.65,roll>.78?'RIVAL SLAM!':'RIVAL STRIKE!')}}
function animate(t){for(const w of [player,enemy]){const moving=w.userData.down<=0&&w.userData.cooldown<=0,s=moving?Math.sin(t*.008)*.12:0;w.userData.limbs[0].rotation.x=s;w.userData.limbs[1].rotation.x=-s;w.userData.limbs[2].rotation.x=w.userData.blocking?-.9:-s;w.userData.limbs[3].rotation.x=w.userData.blocking?-.9:s}}
function updateHud(){$('#pHealth').style.width=`${player.userData.health/player.userData.maxHealth*100}%`;$('#eHealth').style.width=`${enemy.userData.health/enemy.userData.maxHealth*100}%`;$('#pSig').textContent=`${Math.floor(player.userData.signature)}%`;$('#eSig').textContent=`${Math.floor(enemy.userData.signature)}%`}
function show(s){$('#message').textContent=s;$('#message').style.opacity=1;messageTime=1.4}
function end(win){playing=false;$('#count').style.opacity=0;$('#endTitle').textContent=win?'YOU WIN!':'RIVAL WINS';$('#endText').textContent=win?`${player.userData.name} wins by pinfall!`:`${enemy.userData.name} wins the match.`;$('#end').classList.add('show')}
function loop(t){const dt=Math.min((t-last)/1000,.05);last=t;update(dt,t);renderer.render(scene,camera);requestAnimationFrame(loop)}
$('#playBtn').onclick=()=>start(false);$('#watchBtn').onclick=()=>start(true);$('#againBtn').onclick=()=>location.reload();addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.repeat||watchMode)return;if(e.key.toLowerCase()==='f')hit(player,enemy,8,.45,'STRIKE!');if(e.key.toLowerCase()==='g')hit(player,enemy,14,.75,'BIG KICK!');if(e.key.toLowerCase()==='r')grapple();if(e.key.toLowerCase()==='t')signature();if(e.key.toLowerCase()==='p')pin()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);$('#strikeBtn').onclick=()=>hit(player,enemy,8,.45,'STRIKE!');$('#kickBtn').onclick=()=>hit(player,enemy,14,.75,'BIG KICK!');$('#grabBtn').onclick=grapple;$('#slamBtn').onclick=signature;$('#pinBtn').onclick=pin;addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
