import * as THREE from "../creek-games-3d/three.module.js";

const $=s=>document.querySelector(s),scene=new THREE.Scene();scene.background=new THREE.Color('#182321');scene.fog=new THREE.FogExp2('#17211f',.022);
const mount=$('#game'),camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,130),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;mount.append(renderer.domElement);
scene.add(new THREE.HemisphereLight('#9eb1a8','#111a17',1.3));const moon=new THREE.DirectionalLight('#b8d4cf',2.1);moon.position.set(-18,28,15);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);moon.shadow.camera.left=-40;moon.shadow.camera.right=40;moon.shadow.camera.top=40;moon.shadow.camera.bottom=-40;scene.add(moon);
const mat=(c,r=.8,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m}),make=(geo,c,r,m)=>{const o=new THREE.Mesh(geo,mat(c,r,m));o.castShadow=o.receiveShadow=true;return o};
const suspects=[
 {name:'Violet Green',role:'Gardener',color:'#536d4c',item:'a pair of pruning shears',detail:'dark green wool',alibi:'I was repairing the greenhouse irrigation until midnight.'},
 {name:'Miles Crowe',role:'Butler',color:'#454d58',item:'the master service key',detail:'charcoal uniform cloth',alibi:'I was polishing silver in the dining room with Clara nearby.'},
 {name:'Clara Vale',role:'Artist',color:'#78576f',item:'a bottle of crimson paint solvent',detail:'purple velvet thread',alibi:'I painted in the east studio. Miles passed the doorway twice.'},
 {name:'Dr. Rowan Hale',role:'Family Doctor',color:'#6d746f',item:'an engraved medicine vial',detail:'pale gray coat fiber',alibi:'I was reading in the library beside the grandfather clock.'}
];
const culprit=suspects[Math.floor(Math.random()*suspects.length)],keys={},clueObjects=[],characters=[],found=[],questioned=new Set();let playing=false,yaw=0,dialogueOpen=false,caseEnded=false,last=performance.now(),nearTarget=null;
const clueData=[
 {title:'Torn Fabric',text:`A thread of ${culprit.detail} was caught on the study window latch.`,position:[-15,.65,-7],color:'#9dc2ba'},
 {title:'Discarded Object',text:`Hidden beneath the stairs: ${culprit.item}. It appears to have been wiped clean.`,position:[3,.55,-13],color:'#d6b96d'},
 {title:'Muddy Footprint',text:`A wet footprint leads from the crime scene toward the ${culprit.role.toLowerCase()}'s usual room.`,position:[13,.18,1],color:'#806c4f'},
 {title:'Burned Note',text:`The surviving line reads: “Meet ${culprit.name.split(' ')[0]} in the study at eleven. Come alone.”`,position:[-3,.32,10],color:'#d18e5e'},
 {title:'Stopped Watch',text:`The victim's watch stopped at 11:17. This directly contradicts ${culprit.name}'s claimed timeline.`,position:[14,.45,-12],color:'#c9b86b'}
];

createManor();const player=createCharacter('Detective','#334e55');addDetectiveDetails(player);player.position.set(0,0,17);scene.add(player);createSuspects();createClues();const rain=createRain();camera.position.set(8,8,25);renderNotebook();requestAnimationFrame(loop);

function createManor(){const ground=make(new THREE.PlaneGeometry(90,90),'#26332c',1);ground.material.map=createSurfaceTexture('#26332c','#39483d',1200);ground.material.map.wrapS=ground.material.map.wrapT=THREE.RepeatWrapping;ground.material.map.repeat.set(15,15);ground.rotation.x=-Math.PI/2;scene.add(ground);const floor=make(new THREE.BoxGeometry(42,.35,34),'#40382e',.82);floor.material.map=createWoodTexture();floor.material.map.wrapS=floor.material.map.wrapT=THREE.RepeatWrapping;floor.material.map.repeat.set(10,8);floor.position.set(0,.15,0);scene.add(floor);const wallMat='#66645d';for(const [x,y,z,w,h,d] of [[0,3,-17,42,6,.5],[-21,3,0,.5,6,34],[21,3,0,.5,6,34],[-13,3,17,16,6,.5],[13,3,17,16,6,.5]]){const wall=make(new THREE.BoxGeometry(w,h,d),wallMat,.92);wall.position.set(x,y,z);scene.add(wall);const trim=make(new THREE.BoxGeometry(w>.5?w:.14,.18,d>.5?d:.14),'#312b25',.78);trim.position.set(x,.55,z);scene.add(trim)}
 for(const [x,z,rot,len] of [[-8,-7,0,18],[9,4,0,20],[0,-4,Math.PI/2,25]]){const wall=make(new THREE.BoxGeometry(len,4.4,.28),'#4d514c',.95);wall.position.set(x,2.2,z);wall.rotation.y=rot;scene.add(wall)}
 const rug=make(new THREE.PlaneGeometry(9,12),'#4f2028',.9);rug.rotation.x=-Math.PI/2;rug.position.set(0,.36,7);scene.add(rug);for(const [x,z] of [[-16,-12],[16,-12],[-16,12],[16,12]]){const lamp=new THREE.PointLight('#f0bd78',2.2,13);lamp.position.set(x,3.2,z);scene.add(lamp);const table=make(new THREE.CylinderGeometry(.8,.9,.7,16),'#3c2b21',.8);table.position.set(x,.35,z);scene.add(table)}
 createFurniture();addManorDetails();for(let i=0;i<35;i++){const tree=new THREE.Group(),tr=make(new THREE.CylinderGeometry(.25,.4,3,10),'#40352b',1),crown=make(new THREE.IcosahedronGeometry(1.3,2),'#24392d',1);tr.position.y=1.5;crown.position.y=3.5;tree.add(tr,crown);const a=i/35*Math.PI*2,r=28+Math.random()*10;tree.position.set(Math.cos(a)*r,0,Math.sin(a)*r);scene.add(tree)}}
function createSurfaceTexture(base,speck,count){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.fillStyle=base;x.fillRect(0,0,512,512);for(let i=0;i<count;i++){x.globalAlpha=.08+Math.random()*.15;x.fillStyle=i%2?speck:'#151c19';x.beginPath();x.arc(Math.random()*512,Math.random()*512,.5+Math.random()*2.5,0,Math.PI*2);x.fill()}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function createWoodTexture(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.fillStyle='#3f3025';x.fillRect(0,0,512,512);for(let y=0;y<512;y+=32){x.fillStyle=y%64?'#4d392a':'#463326';x.fillRect(0,y,512,30);x.strokeStyle='#241c17';x.strokeRect(0,y,512,31);for(let i=0;i<8;i++){x.globalAlpha=.2;x.strokeStyle='#c09262';x.beginPath();x.moveTo(0,y+Math.random()*28);x.bezierCurveTo(160,y+Math.random()*28,340,y+Math.random()*28,512,y+Math.random()*28);x.stroke()}}x.globalAlpha=1;const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function createFurniture(){for(const [x,z,w,d] of [[-14,-11,5,2],[12,-11,4,2],[-14,8,4,1.5],[14,10,5,2]]){const desk=make(new THREE.BoxGeometry(w,.22,d),'#4a3325',.8);desk.position.set(x,1,z);for(const sx of [-1,1])for(const sz of [-1,1]){const leg=make(new THREE.BoxGeometry(.16,1,.16),'#38271d',.85);leg.position.set(x+sx*(w/2-.2),.5,z+sz*(d/2-.2));scene.add(leg)}scene.add(desk)}for(let i=0;i<5;i++){const shelf=make(new THREE.BoxGeometry(3,3.2,.5),'#35271f',.9);shelf.position.set(-19,1.6,-11+i*5);scene.add(shelf);for(let y=.5;y<3;y+=.6){const books=make(new THREE.BoxGeometry(2.6,.35,.3),i%2?'#59604c':'#68464b',.8);books.position.set(-18.7,y,-11+i*5);scene.add(books)}}const stairs=new THREE.Group();for(let i=0;i<8;i++){const step=make(new THREE.BoxGeometry(4,.35,1.2),'#504438',.9);step.position.set(5,i*.35+.18,-13+i*.7);stairs.add(step)}scene.add(stairs)}
function addManorDetails(){for(const x of [-15,-8,8,15]){const window=new THREE.Mesh(new THREE.PlaneGeometry(3,2.7),new THREE.MeshPhysicalMaterial({color:'#88a7ac',transparent:true,opacity:.35,roughness:.12,metalness:.08}));window.position.set(x,3,-16.73);scene.add(window);for(const sx of [-1,1]){const curtain=make(new THREE.BoxGeometry(.55,3,.16),'#572c34',.82);curtain.position.set(x+sx*1.7,3,-16.55);scene.add(curtain)}}for(let i=0;i<3;i++){const fixture=new THREE.Group(),chain=make(new THREE.CylinderGeometry(.025,.025,1.5,8),'#3b342b',.45,.6),light=new THREE.PointLight('#efc37f',1.8,12),shade=new THREE.Mesh(new THREE.ConeGeometry(.6,.5,20,1,true),new THREE.MeshStandardMaterial({color:'#d6b979',transparent:true,opacity:.58,side:THREE.DoubleSide}));chain.position.y=5.2;shade.position.y=4.3;light.position.y=4.25;fixture.add(chain,shade,light);fixture.position.set(-11+i*11,0,4);scene.add(fixture)}for(const [x,z,c] of [[-20,-6,'#604a3b'],[20,-2,'#3d5456'],[-3,-16.7,'#6a4940']]){const frame=make(new THREE.BoxGeometry(2.2,2.8,.12),'#2b211a',.65,.2),art=make(new THREE.PlaneGeometry(1.8,2.4),c,.75);frame.position.set(x,3,z);art.position.set(x+(x===-20?.07:x===20?-.07:0),3,z+(z< -16?.07:0));if(x!==0){frame.rotation.y=art.rotation.y=Math.PI/2}scene.add(frame,art)}}
function createCharacter(name,color){const g=new THREE.Group(),cloth=mat(color,.76),skin=mat('#b98b68',.7),dark=mat('#252a2a',.75),body=new THREE.Mesh(new THREE.CapsuleGeometry(.34,.72,7,16),cloth);body.scale.set(1,.98,.72);body.position.y=1.35;const shirt=make(new THREE.BoxGeometry(.34,.55,.12),'#d1c8b5',.7);shirt.position.set(0,1.48,.29);const collarL=make(new THREE.BoxGeometry(.18,.28,.07),'#eee5d1',.7),collarR=collarL.clone();collarL.position.set(-.1,1.72,.37);collarR.position.set(.1,1.72,.37);collarL.rotation.z=-.35;collarR.rotation.z=.35;const head=new THREE.Mesh(new THREE.SphereGeometry(.29,24,18),skin);head.scale.set(.9,1.08,.93);head.position.y=2.16;const nose=new THREE.Mesh(new THREE.SphereGeometry(.045,10,8),skin);nose.scale.set(.75,1,1.2);nose.position.set(0,2.14,.275);const hair=make(new THREE.SphereGeometry(.315,20,14,0,Math.PI*2,0,Math.PI*.58),'#30241f',.88);hair.position.y=2.3;for(const x of [-.105,.105]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.022,8,6),new THREE.MeshBasicMaterial({color:'#1b1d1c'}));eye.position.set(x,2.2,.27);g.add(eye)}const legs=[],arms=[];for(const x of [-.19,.19]){const leg=new THREE.Group(),limb=new THREE.Mesh(new THREE.CapsuleGeometry(.095,.44,5,10),dark),shoe=make(new THREE.BoxGeometry(.2,.14,.34),'#171a19',.65,.15);limb.position.y=-.27;shoe.position.set(0,-.63,.07);leg.position.set(x,.82,0);leg.add(limb,shoe);legs.push(leg);g.add(leg)}for(const x of [-.43,.43]){const arm=new THREE.Group(),sleeve=new THREE.Mesh(new THREE.CapsuleGeometry(.09,.42,5,10),cloth),hand=new THREE.Mesh(new THREE.SphereGeometry(.1,10,8),skin);sleeve.position.y=-.25;hand.position.y=-.57;arm.position.set(x,1.67,0);arm.rotation.z=x>0?-.08:.08;arm.add(sleeve,hand);arms.push(arm);g.add(arm)}g.add(body,shirt,collarL,collarR,head,nose,hair);g.userData={name,legs,arms};g.traverse(o=>{if(o.isMesh)o.castShadow=true});return g}
function addDetectiveDetails(g){const coat=make(new THREE.BoxGeometry(.78,.95,.18),'#273c42',.8);coat.position.set(0,1.22,-.23);const brim=make(new THREE.CylinderGeometry(.42,.42,.055,24),'#202b2e',.76);brim.position.y=2.4;const crown=make(new THREE.CylinderGeometry(.29,.33,.36,20),'#28373b',.78);crown.position.y=2.57;g.add(coat,brim,crown)}
function createRain(){const count=850,geo=new THREE.BufferGeometry(),positions=new Float32Array(count*3);for(let i=0;i<count;i++){positions[i*3]=(Math.random()-.5)*80;positions[i*3+1]=Math.random()*24;positions[i*3+2]=(Math.random()-.5)*80}geo.setAttribute('position',new THREE.BufferAttribute(positions,3));const rain=new THREE.Points(geo,new THREE.PointsMaterial({color:'#a9c2c3',size:.045,transparent:true,opacity:.5}));scene.add(rain);return rain}
function createSuspects(){const positions=[[-14,0],[13,-8],[-12,11],[14,10]];suspects.forEach((s,i)=>{const c=createCharacter(s.name,s.color);addRoleDetails(c,s.role);c.position.set(positions[i][0],0,positions[i][1]);c.userData.suspect=s;characters.push(c);scene.add(c);const tag=createTag(`${s.name}\n${s.role}`);tag.position.y=2.95;c.add(tag)})}
function addRoleDetails(c,role){if(role==='Gardener'){const apron=make(new THREE.BoxGeometry(.58,.72,.1),'#425c3d',.86);apron.position.set(0,1.3,.37);const hat=make(new THREE.CylinderGeometry(.4,.4,.06,20),'#7b6947',.95);hat.position.y=2.43;c.add(apron,hat)}else if(role==='Butler'){const bow=new THREE.Mesh(new THREE.OctahedronGeometry(.11),mat('#251d1d',.55));bow.scale.set(1.5,.7,.5);bow.position.set(0,1.72,.44);c.add(bow)}else if(role==='Artist'){const scarf=make(new THREE.TorusGeometry(.25,.055,8,20),'#9b434b',.7);scarf.rotation.x=Math.PI/2;scarf.position.y=1.86;c.add(scarf)}else{const stethoscope=make(new THREE.TorusGeometry(.23,.025,8,24),'#282e30',.35,.45);stethoscope.position.set(0,1.54,.41);c.add(stethoscope)}}
function createTag(text){const c=document.createElement('canvas');c.width=380;c.height=90;const x=c.getContext('2d');x.fillStyle='#101817dd';x.fillRect(0,0,380,90);x.fillStyle='#e7d8b8';x.font='bold 25px Georgia';x.textAlign='center';x.fillText(text.split('\n')[0],190,34);x.fillStyle='#9ba99f';x.font='18px Arial';x.fillText(text.split('\n')[1]||'',190,64);const t=new THREE.CanvasTexture(c),s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.scale.set(3.3,.78,1);return s}
function createClues(){clueData.forEach((data,i)=>{let object;if(i===0)object=make(new THREE.BoxGeometry(.5,.06,.3),data.color,.8);else if(i===1)object=make(new THREE.BoxGeometry(.65,.13,.2),data.color,.4,.35);else if(i===2)object=make(new THREE.PlaneGeometry(.75,1.1),data.color,.9);else if(i===3)object=make(new THREE.PlaneGeometry(.8,.55),data.color,.8);else object=make(new THREE.CylinderGeometry(.28,.28,.1,18),data.color,.3,.65);if(i===2||i===3)object.rotation.x=-Math.PI/2;object.position.set(...data.position);const glow=new THREE.PointLight(data.color,1.5,4);glow.position.y=.6;object.add(glow);object.userData={clue:data,index:i,phase:Math.random()*8};clueObjects.push(object);scene.add(object)})}
function nearestInteractable(){let best=null,d=2.35;for(const clue of clueObjects){if(clue.userData.found)continue;const n=player.position.distanceTo(clue.position);if(n<d){d=n;best={type:'clue',object:clue}}}for(const c of characters){const n=player.position.distanceTo(c.position);if(n<d){d=n;best={type:'character',object:c}}}return best}
function interact(){if(!playing||caseEnded)return;if(dialogueOpen){closeDialogue();return}nearTarget=nearestInteractable();if(!nearTarget)return;if(nearTarget.type==='clue')collectClue(nearTarget.object);else question(nearTarget.object)}
function collectClue(object){object.userData.found=true;object.visible=false;found.push(object.userData.clue);showDialogue('Evidence Found',`${object.userData.clue.title}: ${object.userData.clue.text}`);renderNotebook();updateHud()}
function question(character){const s=character.userData.suspect;questioned.add(s.name);const guilty=s===culprit,text=guilty?`${s.alibi} Why are you asking me? You should investigate someone else.`:`${s.alibi} I also remember seeing ${culprit.name.split(' ')[0]} acting nervous near the study.`;showDialogue(`${s.name} — ${s.role}`,text);renderNotebook();updateHud()}
function showDialogue(name,text){dialogueOpen=true;$('#speaker').textContent=name;$('#dialogueText').textContent=text;$('#dialogue').style.display='block'}function closeDialogue(){dialogueOpen=false;$('#dialogue').style.display='none'}
function renderNotebook(){$('#evidenceList').innerHTML=found.length?found.map(c=>`<article class="evidence"><b>${c.title}</b><p>${c.text}</p></article>`).join(''):'<p>No evidence collected yet.</p>';$('#suspectList').innerHTML=suspects.map(s=>`<article class="suspect"><b>${s.name}</b><p>${s.role} · ${questioned.has(s.name)?'Questioned':'Not questioned'}</p></article>`).join('');$('#accuseBtn').disabled=found.length<3;$('#caseHint').textContent=found.length<3?`Find ${3-found.length} more clue${3-found.length===1?'':'s'} to unlock an accusation.`:'You have enough evidence to make an accusation—or keep investigating.'}
function updateHud(){$('#clueCount').textContent=`${found.length} / ${clueData.length}`;$('#talkCount').textContent=`${questioned.size} / ${suspects.length}`}
function openAccusation(){$('#accuseChoices').innerHTML=suspects.map((s,i)=>`<button class="choice" data-index="${i}"><b>${s.name}</b> — ${s.role}</button>`).join('');$('#accusation').classList.add('show');document.exitPointerLock?.();document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>accuse(suspects[Number(b.dataset.index)]))}
function accuse(suspect){caseEnded=true;$('#accusation').classList.remove('show');const correct=suspect===culprit;$('#endingTitle').textContent=correct?'CASE SOLVED':'WRONG ACCUSATION';$('#endingText').textContent=correct?`${suspect.name}, the ${suspect.role.toLowerCase()}, committed the murder. Your evidence exposed the truth.`:`${suspect.name} was innocent. The real murderer was ${culprit.name}, the ${culprit.role.toLowerCase()}.`;$('#caseStatus').textContent=correct?'Solved':'Failed';$('#ending').classList.add('show')}
function updatePlayer(dt,time){if(dialogueOpen||$('#notebook').classList.contains('open')||$('#accusation').classList.contains('show'))return;const f=(keys.w||keys.ArrowUp?1:0)-(keys.s||keys.ArrowDown?1:0),r=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),len=Math.hypot(f,r);if(len){const sy=Math.sin(yaw),cy=Math.cos(yaw),dx=(-sy*f+cy*r)/len,dz=(-cy*f-sy*r)/len;player.position.x=Math.max(-19.8,Math.min(19.8,player.position.x+dx*dt*5));player.position.z=Math.max(-16.4,Math.min(22,player.position.z+dz*dt*5));player.rotation.y=Math.atan2(dx,dz);const swing=Math.sin(time*.012)*.5;player.userData.legs[0].rotation.x=swing;player.userData.legs[1].rotation.x=-swing;player.userData.arms[0].rotation.x=-swing*.7;player.userData.arms[1].rotation.x=swing*.7}else{player.userData.legs.forEach(l=>l.rotation.x*=.8);player.userData.arms.forEach(a=>a.rotation.x*=.8)};const behind=new THREE.Vector3(Math.sin(yaw)*8,5.7,Math.cos(yaw)*8);camera.position.lerp(player.position.clone().add(behind),.08);camera.lookAt(player.position.x,1.2,player.position.z)}
function updateRain(dt){rain.visible=player.position.z>17.15;const p=rain.geometry.attributes.position.array;for(let i=0;i<p.length;i+=3){p[i+1]-=dt*15;if(p[i+1]<0){p[i]=player.position.x+(Math.random()-.5)*70;p[i+1]=20+Math.random()*6;p[i+2]=player.position.z+(Math.random()-.5)*70}}rain.geometry.attributes.position.needsUpdate=true}
function loop(time){const dt=Math.min((time-last)/1000,.05);last=time;if(playing){updatePlayer(dt,time);updateRain(dt)}for(const c of clueObjects){if(c.userData.found)continue;c.rotation.y+=dt*.6;c.position.y+=Math.sin(time*.003+c.userData.phase)*.001}nearTarget=playing?nearestInteractable():null;$('#prompt').style.opacity=nearTarget&&!dialogueOpen?1:0;$('#prompt').textContent=nearTarget?nearTarget.type==='clue'?'E — Examine clue':`E — Question ${nearTarget.object.userData.suspect.name}`:'';renderer.render(scene,camera);requestAnimationFrame(loop)}

$('#playBtn').onclick=()=>{$('#start').classList.add('hide');playing=true;renderer.domElement.requestPointerLock?.()};$('#notebookBtn').onclick=()=>{$('#notebook').classList.add('open');document.exitPointerLock?.()};$('#closeNotebook').onclick=()=>$('#notebook').classList.remove('open');$('#accuseBtn').onclick=openAccusation;$('#closeAccusation').onclick=()=>$('#accusation').classList.remove('show');$('#againBtn').onclick=()=>location.reload();$('#actionBtn').onclick=interact;addEventListener('keydown',e=>{keys[e.key]=true;if((e.key==='e'||e.key==='E')&&!e.repeat)interact();if((e.key==='n'||e.key==='N')&&!e.repeat)$('#notebook').classList.toggle('open')});addEventListener('keyup',e=>keys[e.key]=false);renderer.domElement.onclick=()=>{if(playing&&!dialogueOpen)renderer.domElement.requestPointerLock?.()};addEventListener('mousemove',e=>{if(document.pointerLockElement===renderer.domElement)yaw-=e.movementX*.0025});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});document.querySelectorAll('[data-key]').forEach(b=>{for(const ev of ['pointerdown','pointerup','pointercancel','pointerleave'])b.addEventListener(ev,e=>{keys[b.dataset.key]=ev==='pointerdown';e.preventDefault()})});
