import * as THREE from "../creek-games-3d/three.module.js";

const TYPES=[
 ['Water','Common','#45cfff'],['Plant','Common','#68c85a'],['Fire','Common','#ff6b35'],['Burger','Common','#f2a93b'],['Cold','Common','#9bd7ff'],
 ['Fried','Rare','#f1cc54'],['Crab','Rare','#ef6259'],['Firework','Rare','#e7539b'],['Hug','Rare','#f78fbb'],['Bird','Rare','#7bd5da'],
 ['Soccer','Epic','#58a34d'],['Ghoul','Epic','#7f57a8'],['Guardian','Epic','#f09b5f'],['Cat','Epic','#697887'],['Witch','Epic','#633c9b'],
 ['Neymar Jr','Mythic','#49a44b'],['Rick Grimes','Mythic','#966b4e'],['Astronaut','Mythic','#e7e9ef'],['Spider Man','Mythic','#ef4949'],['Toasted Marshmallow','Mythic','#e7cfaa'],['12 PM','Mythic','#ff9b45'],
 ['Onion Sprout','Legendary','#91d979'],['Money Bandit','Legendary','#4bb773'],['Rock','Legendary','#9a70c7'],['Super','Legendary','#4f7dea'],['Lucid','Legendary','#a4b3d8'],['Gemstone','Legendary','#9b5def'],['Ninja','Legendary','#252c49'],
 ['Galaxy','God','#5f53d9'],['Sphere','God','#ff6fcf'],['Radioactive','God','#b9f331'],['Dessert','God','#ff82b6'],['Psycho','God','#ef3e62']
].map((x,i)=>({name:x[0],rarity:x[1],color:x[2],id:i}));
const rank={Common:0,Rare:1,Epic:2,Mythic:3,Legendary:4,God:5}, values=[5,12,28,65,150,500], weights=[45,25,14,8,5,3];
const MUTATIONS=[{name:'Gold',color:'#ffd447',multiplier:2},{name:'Diamond',color:'#72eaff',multiplier:3},{name:'Yummi',color:'#ff79bd',multiplier:4},{name:'Jhonso',color:'#8cff4f',accent:'#ff8b35',multiplier:5},{name:'Void',color:'#21133f',accent:'#d84cff',multiplier:7},{name:'Cyber',color:'#6d39da',accent:'#38f5ff',multiplier:6},{name:'Gem',color:'#ffffff',accent:'#c9f7ff',multiplier:8}];
const mount=document.querySelector('#game'), scene=new THREE.Scene(); scene.background=new THREE.Color('#63c9ff'); scene.fog=new THREE.FogExp2('#9ce3ff',.012);
const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,160), renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15; mount.append(renderer.domElement);
scene.add(new THREE.HemisphereLight('#dff6ff','#507c39',2.2)); const sun=new THREE.DirectionalLight('#fff0c2',3.2); sun.position.set(-18,30,14); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;sun.shadow.bias=-.0003; scene.add(sun);
const mat=(c,rough=.68,metal=0)=>new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal}); const box=(x,y,z,c,r=.68)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),mat(c,r));m.castShadow=m.receiveShadow=true;return m};
createWorld();
const base=createBase();base.position.set(0,0,23);scene.add(base);
const player=createPlayer();player.position.set(0,0,19);scene.add(player);
const keys={}, state=JSON.parse(localStorage.getItem('stealAPico')||'{"coins":0,"caught":{}}'),aiBases=[],wildPicos=[],bookProgress=document.querySelector('#progress'),picoGridElement=document.querySelector('#picoGrid'),mutationGridElement=document.querySelector('#mutationGrid'),mutationPicoGrid=document.querySelector('#mutationPicoGrid'),mutationDetailTitle=document.querySelector('#mutationDetailTitle'),mutationDetailSummary=document.querySelector('#mutationDetailSummary');state.mutations??={};state.mutationPicos??={}; let carried=null,playing=false,last=performance.now(),spawnTimer=0,aiStockTimer=12,worldTime=0,powerEffect=null,powerReadyAt=0;
function eye(x){const e=new THREE.Mesh(new THREE.SphereGeometry(.09,12,10),mat('#10152a',.3));e.position.set(x,1.55,.79);return e}
function makePico(type){const g=new THREE.Group(),tier=rank[type.rarity],skin=mat(type.color,.38,tier>3?.1:0);const baseBlob=new THREE.Mesh(new THREE.SphereGeometry(1.05,32,22),skin);baseBlob.scale.set(1.45,.72,.95);baseBlob.position.y=.72;const top=new THREE.Mesh(new THREE.SphereGeometry(.76,32,22),skin);top.scale.set(.82,1.3,.78);top.position.y=1.35;g.add(baseBlob,top,eye(-.25),eye(.25));const smile=new THREE.Mesh(new THREE.TorusGeometry(.23,.04,8,20,Math.PI),mat('#10152a',.25));smile.rotation.z=Math.PI;smile.position.set(0,1.26,.82);g.add(smile);for(const x of [-1.12,1.12]){const foot=new THREE.Mesh(new THREE.SphereGeometry(.48,20,12),skin);foot.scale.set(1.2,.35,.75);foot.position.set(x,.34,0);g.add(foot)}
 if(tier>=2){const halo=new THREE.Mesh(new THREE.TorusGeometry(1.45,.07,10,48),new THREE.MeshBasicMaterial({color:type.color,transparent:true,opacity:.8}));halo.rotation.x=Math.PI/2;halo.position.y=.25;g.add(halo);const light=new THREE.PointLight(type.color,tier*.45,5);light.position.y=1.3;g.add(light)}
 addPicoCostume(g,type,skin);g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});g.userData.type=type;return g}
function createWorld(){
 const ground=new THREE.Mesh(new THREE.CylinderGeometry(36,38,2,64),mat('#69b94e',.92));ground.position.y=-1;ground.receiveShadow=true;scene.add(ground);
 for(const [x,z,r,h] of [[-21,-12,8,1.3],[18,-14,9,1.1],[-18,14,7,1],[17,13,8,1.4]]){const ledge=new THREE.Mesh(new THREE.CylinderGeometry(r,r+.7,h,32),mat('#77c85a',.9));ledge.position.set(x,h/2-.05,z);ledge.receiveShadow=true;scene.add(ledge);const soil=new THREE.Mesh(new THREE.CylinderGeometry(r+.02,r+.75,h*.55,32),mat('#9a6b3e',1));soil.position.set(x,-h*.2,z);scene.add(soil)}
 for(let i=0;i<54;i++){const a=i/54*Math.PI*2,r=28+Math.sin(i*8)*2.4;createTree(Math.cos(a)*r,Math.sin(a)*r,(i%4)*.15+1)}
 for(let i=0;i<90;i++){const x=(Math.random()-.5)*52,z=(Math.random()-.5)*52;if(Math.hypot(x,z-23)<7)continue;createFlower(x,z,['#fff7d2','#ff83aa','#7fdfff','#ffd453'][i%4],.65+Math.random()*.5)}
 for(let i=0;i<12;i++){const c=new THREE.Group();for(let j=0;j<4;j++){const puff=new THREE.Mesh(new THREE.SphereGeometry(1.4+j*.15,16,12),new THREE.MeshBasicMaterial({color:'#fff',transparent:true,opacity:.82}));puff.scale.y=.6;puff.position.set(j*1.25,Math.sin(j)*.25,0);c.add(puff)}c.position.set(-35+i*7,13+(i%3)*2,-25-i%2*8);scene.add(c)}
}
function createTree(x,z,s=1){const t=new THREE.Group(),tr=new THREE.Mesh(new THREE.CylinderGeometry(.38,.55,3,10),mat('#8c5934',.95));tr.position.y=1.5;tr.castShadow=true;t.add(tr);for(const [dx,dy,dz,k] of [[0,3.3,0,1.5],[-.8,3,.1,1],[.8,3.1,0,1.15],[0,3.2,.7,1]]){const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(k,2),mat('#55a947',.9));crown.position.set(dx,dy,dz);crown.castShadow=true;t.add(crown)}t.scale.setScalar(s);t.position.set(x,0,z);scene.add(t)}
function createFlower(x,z,c,s){const g=new THREE.Group(),stem=new THREE.Mesh(new THREE.CylinderGeometry(.025,.035,.42,7),mat('#3c942f'));stem.position.y=.21;g.add(stem);for(let i=0;i<5;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.1,8,6),mat(c,.5));p.scale.set(1.3,.45,1);p.position.set(Math.cos(i*1.256)*.12,.46,Math.sin(i*1.256)*.12);g.add(p)}g.scale.setScalar(s);g.position.set(x,0,z);scene.add(g)}
function createBase(){const g=new THREE.Group(),stone=mat('#d8caa7',.82),purple=mat('#6b54c7',.45,.12);const pad=new THREE.Mesh(new THREE.CylinderGeometry(5.5,5.8,.5,48),purple);pad.position.y=.25;pad.receiveShadow=true;g.add(pad);for(let i=0;i<3;i++){const step=new THREE.Mesh(new THREE.CylinderGeometry(4.7-i*.42,5-i*.42,.45,48),stone);step.position.set(0,.48+i*.38,2.1+i*.25);g.add(step)}
 for(const x of [-3.4,3.4]){const tower=new THREE.Mesh(new THREE.CylinderGeometry(1.55,1.8,5.7,20),purple);tower.position.set(x,3.6,2.4);g.add(tower);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.85,1.3,20),mat(x<0?'#5dc9ff':'#a45eff',.3,.15));roof.position.set(x,7.05,2.4);g.add(roof)}
 const arch=new THREE.Mesh(new THREE.BoxGeometry(5.8,5.1,1.6),stone);arch.position.set(0,3.35,2.8);g.add(arch);const portal=new THREE.Mesh(new THREE.PlaneGeometry(3.4,3.7),new THREE.MeshBasicMaterial({color:'#8df5ff',transparent:true,opacity:.75}));portal.position.set(0,3.1,1.96);g.add(portal);const glow=new THREE.PointLight('#75efff',3.5,11);glow.position.set(0,3,0);g.add(glow);
 for(let i=0;i<5;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(3.65+i*.08,.04,8,48),new THREE.MeshBasicMaterial({color:i%2?'#fff49c':'#8df5ff'}));ring.rotation.x=Math.PI/2;ring.position.y=.57+i*.015;g.add(ring)}g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});return g}
function createPlayer(){const g=new THREE.Group(),skin=mat('#ffc493',.55),shirt=mat('#1ea899',.55),shorts=mat('#293a68',.7),shoe=mat('#f6f2df',.55);const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.53,1.05,6,14),shirt);torso.position.y=1.72;const head=new THREE.Mesh(new THREE.SphereGeometry(.6,24,18),skin);head.position.y=2.85;const hair=new THREE.Mesh(new THREE.SphereGeometry(.65,20,14,0,Math.PI*2,0,Math.PI*.5),mat('#54311f',.85));hair.position.y=3.03;g.add(torso,head,hair);const limbs=[];for(const x of [-.37,.37]){const leg=new THREE.Group(),calf=new THREE.Mesh(new THREE.CapsuleGeometry(.15,.72,5,10),skin);calf.position.y=-.5;const sneaker=new THREE.Mesh(new THREE.SphereGeometry(.25,14,10),shoe);sneaker.scale.set(1, .65,1.45);sneaker.position.set(0,-1,.12);leg.add(calf,sneaker);leg.position.set(x,1.05,0);g.add(leg);limbs.push(leg)}for(const x of [-.72,.72]){const arm=new THREE.Group(),a=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.75,5,10),skin);a.position.y=-.45;arm.add(a);arm.position.set(x,2.1,0);arm.rotation.z=x>0?-.2:.2;g.add(arm);limbs.push(arm)}const backpack=box(.75,.95,.35,'#e2a83d',.7);backpack.position.set(0,1.8,-.55);g.add(backpack);const aura=new THREE.Mesh(new THREE.TorusGeometry(1.05,.09,10,40),new THREE.MeshBasicMaterial({color:'#fff',transparent:true,opacity:.8}));aura.rotation.x=Math.PI/2;aura.position.y=.2;aura.visible=false;g.add(aura);g.userData.limbs=limbs;g.userData.aura=aura;g.traverse(o=>{if(o.isMesh)o.castShadow=true});return g}
function addPicoCostume(g,type,skin){const n=type.name,add=(mesh,x=0,y=2.3,z=0)=>{mesh.position.set(x,y,z);g.add(mesh)};
 if(['Cat','Bird'].includes(n)){for(const x of [-.5,.5])add(new THREE.Mesh(new THREE.ConeGeometry(.28,.65,4),skin),x,2.15,0)}
 if(['Witch','Money Bandit','Ninja','Rock'].includes(n)){const brim=new THREE.Mesh(new THREE.CylinderGeometry(.95,.95,.1,24),mat(n==='Witch'?'#3c2360':'#282c3d',.55));add(brim,0,2.1,0);add(new THREE.Mesh(new THREE.ConeGeometry(.68,1.25,16),brim.material),0,2.75,0)}
 if(n==='Gemstone')add(new THREE.Mesh(new THREE.OctahedronGeometry(.5),mat('#e69bff',.18,.35)),0,2.65,0);
 if(n==='Fire')for(let i=0;i<3;i++)add(new THREE.Mesh(new THREE.ConeGeometry(.35,.9,9),mat(i===1?'#ffe15a':'#ff713c',.35)),(i-1)*.3,2.4-i%2*.15,0);
 if(n==='Burger'){for(const [y,c,r] of [[2.05,'#e7a341',.75],[2.22,'#59a83d',.72],[2.38,'#e55039',.68],[2.55,'#f0b44f',.75]])add(new THREE.Mesh(new THREE.CylinderGeometry(r,r,.17,24),mat(c,.55)),0,y,0)}
 if(n==='Astronaut'){const helmet=new THREE.Mesh(new THREE.SphereGeometry(.9,24,18),new THREE.MeshPhysicalMaterial({color:'#bdecff',transparent:true,opacity:.28,roughness:.08,metalness:.1}));add(helmet,0,1.55,0)}
 if(['Soccer','Neymar Jr'].includes(n)){const ball=new THREE.Mesh(new THREE.IcosahedronGeometry(.38,2),mat('#f7f6ea'));add(ball,0,2.55,0)}
 if(n==='Galaxy')for(let i=0;i<9;i++){const star=new THREE.Mesh(new THREE.SphereGeometry(.055,7,5),new THREE.MeshBasicMaterial({color:'#fff5a6'}));add(star,Math.sin(i*4)*.65,.8+(i%4)*.38,.78)}
 if(n==='Dessert')for(let i=0;i<3;i++){const layer=new THREE.Mesh(new THREE.TorusGeometry(.55-i*.08,.09,7,24),mat(['#fff0d2','#ff89b7','#7de0f0'][i],.5));layer.rotation.x=Math.PI/2;add(layer,0,1.55+i*.24,0)}
}
function createRivals(){
 const rivals=[['Ruby Bot','#ef526f',-21,-12],['Blue Bot','#468bf1',18,-14],['Gold Bot','#f2b83e',-18,14]];
 for(const [name,color,x,z] of rivals){const group=new THREE.Group(),pad=new THREE.Mesh(new THREE.CylinderGeometry(4.2,4.5,.55,32),mat(color,.5,.12));pad.position.y=.28;group.add(pad);const vault=box(5.1,3.7,3.5,'#f3ead2',.75);vault.position.set(0,2.15,1);group.add(vault);const door=box(2.25,2.65,.25,color,.35);door.position.set(0,1.6,-.82);group.add(door);for(const sx of [-2.1,2.1]){const tower=new THREE.Mesh(new THREE.CylinderGeometry(.8,1,4.6,16),mat(color,.48,.1));tower.position.set(sx,2.5,1);group.add(tower);const cap=new THREE.Mesh(new THREE.ConeGeometry(1.05,1.2,16),mat('#fff1bd',.55));cap.position.set(sx,5.3,1);group.add(cap)}const beacon=new THREE.PointLight(color,2.5,8);beacon.position.y=2.5;group.add(beacon);group.position.set(x,0,z);group.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(group);
  const bot=createBot(color);bot.position.set(x,0,z-5);scene.add(bot);const rival={name,color,group,bot,home:new THREE.Vector3(x,0,z),stock:[],display:null,stealCooldown:0,phase:Math.random()*9};for(let i=0;i<3;i++)rival.stock.push(pick());aiBases.push(rival);refreshRivalDisplay(rival)
 }
}
function createMutationLabel(text,color){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=110;const c=canvas.getContext('2d');c.fillStyle='#17233de8';c.roundRect(5,5,502,100,24);c.fill();c.strokeStyle=color;c.lineWidth=8;c.stroke();c.fillStyle='#fff';c.font='900 38px system-ui';c.textAlign='center';c.textBaseline='middle';c.fillText(text,256,56);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true}));sprite.scale.set(4.7,1,1);return sprite}
function mutatePico(pico,mutation,announce=true){if(pico.userData.mutation)return;pico.userData.mutation=mutation;pico.traverse(o=>{if(!o.isMesh||!o.material?.color)return;const hsl={};o.material.color.getHSL(hsl);if(hsl.l<.12)return;o.material=o.material.clone();o.material.color.lerp(new THREE.Color(mutation.color),.9);if(o.material.isMeshStandardMaterial){o.material.emissive.set(mutation.accent||mutation.color);o.material.emissiveIntensity=mutation.name==='Cyber'?.7:mutation.name==='Gem'?.28:.22;if(mutation.name==='Gold'){o.material.metalness=.78;o.material.roughness=.16}if(mutation.name==='Diamond'){o.material.metalness=.3;o.material.roughness=.04}if(mutation.name==='Yummi')o.material.roughness=.25;if(mutation.name==='Cyber')o.material.metalness=.5;if(mutation.name==='Gem'){o.material.metalness=.1;o.material.roughness=.035}}});const ring=new THREE.Mesh(new THREE.TorusGeometry(1.65,.055,8,64),new THREE.MeshBasicMaterial({color:mutation.accent||mutation.color,transparent:true,opacity:.72}));ring.rotation.x=Math.PI/2;ring.position.y=1;pico.add(ring);const badge=createMutationLabel(`${mutation.name.toUpperCase()} x${mutation.multiplier}`,mutation.color);badge.scale.set(2.7,.58,1);badge.position.set(0,3.15,0);pico.add(badge);const glow=new THREE.PointLight(mutation.accent||mutation.color,mutation.name==='Gem'?4.2:3.5,7);glow.position.y=1.4;pico.add(glow);const sparkCount=mutation.name==='Gem'?14:5;for(let i=0;i<sparkCount;i++){const spark=new THREE.Mesh(new THREE.OctahedronGeometry(mutation.name==='Gem'?.13:.09,0),new THREE.MeshBasicMaterial({color:i%3===0?'#ffffff':mutation.accent||'#fff',transparent:true,opacity:.8}));spark.position.set(Math.cos(i*2.399)*1.35,.45+(i%5)*.43,Math.sin(i*2.399)*1.1);spark.userData.gemSpark=mutation.name==='Gem';pico.add(spark)}if(mutation.name==='Gem'){const crystalMaterial=new THREE.MeshPhysicalMaterial({color:'#f5fdff',emissive:'#bdefff',emissiveIntensity:.18,roughness:.015,metalness:0,transmission:.68,thickness:.8,ior:1.52,clearcoat:1,clearcoatRoughness:.02,iridescence:1,iridescenceIOR:1.3,iridescenceThicknessRange:[180,420],flatShading:true});for(let i=0;i<12;i++){const crystal=new THREE.Mesh(new THREE.ConeGeometry(.16+.06*(i%3),.65+.2*(i%3),6),crystalMaterial);const angle=i*Math.PI*2/12;crystal.position.set(Math.cos(angle)*(.72+(i%2)*.38),.6+(i%4)*.42,Math.sin(angle)*(.62+(i%2)*.3));crystal.rotation.z=Math.cos(angle)*.62;crystal.rotation.x=Math.sin(angle)*.62;crystal.userData.gemCrystal=true;crystal.castShadow=true;pico.add(crystal)}}if(announce)toast(`${pico.userData.type.name} became ${mutation.name}! Rewards x${mutation.multiplier}`);if(carried===pico)mutationValue.textContent=`${mutation.name} x${mutation.multiplier}`}
function updateGemSparkles(pico,time){if(pico?.userData.mutation?.name!=='Gem')return;pico.traverse(o=>{if(o.userData.gemSpark){const twinkle=.45+Math.sin(time*.009+o.id*1.7)*.55;o.scale.setScalar(.35+twinkle*1.15);o.material.opacity=.12+twinkle*.88;o.rotation.y+=.035}if(o.userData.gemCrystal){o.rotation.y+=.004;o.material.iridescence=Math.max(.35,.72+Math.sin(time*.002+o.id)*.28)}})}
function createBot(color){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.45,.85,5,12),mat(color,.45,.1));body.position.y=1.3;const head=new THREE.Mesh(new THREE.SphereGeometry(.48,18,14),mat('#c9dded',.32,.25));head.position.y=2.35;const visor=box(.62,.18,.08,'#17233d',.25);visor.position.set(0,2.38,.46);g.add(body,head,visor);for(const x of [-.28,.28]){const leg=box(.18,.7,.2,'#34435e');leg.position.set(x,.42,0);g.add(leg)}g.traverse(o=>{if(o.isMesh)o.castShadow=true});return g}
function refreshRivalDisplay(rival){if(rival.display)scene.remove(rival.display);if(!rival.stock.length){rival.display=null;return}const type=rival.stock[rival.stock.length-1];rival.display=makePico(type);if(type.storedMutation)mutatePico(rival.display,type.storedMutation,false);rival.display.scale.setScalar(.58);rival.display.position.copy(rival.home).add(new THREE.Vector3(0,1.05,-1.5));rival.display.rotation.y=Math.PI;scene.add(rival.display)}
function stealFrom(rival){const type=rival.stock.pop();if(!type)return;carried=makePico(type);if(type.storedMutation)mutatePico(carried,type.storedMutation,false);carried.scale.setScalar(.55);carried.userData.stolenFrom=rival;scene.add(carried);rival.stealCooldown=6;refreshRivalDisplay(rival);toast(`You stole ${rival.name}'s ${type.storedMutation?type.storedMutation.name+' ':''}${type.name} Pico! RUN HOME!`)}
function aiCollect(rival,type,mutation){const stored=mutation?{...type,storedMutation:mutation}:type;rival.stock.push(stored);refreshRivalDisplay(rival);toast(`${rival.name} grabbed the wild ${mutation?mutation.name+' ':''}${type.name} Pico!`)}
function updateRivals(dt,time){aiStockTimer-=dt;if(aiStockTimer<=0){const rival=aiBases[Math.floor(Math.random()*aiBases.length)];rival.stock.push(pick());refreshRivalDisplay(rival);aiStockTimer=10+Math.random()*7}
 for(const rival of aiBases){rival.stealCooldown=Math.max(0,rival.stealCooldown-dt);const nearest=wildPicos.reduce((best,pico)=>!best||rival.bot.position.distanceTo(pico.position)<rival.bot.position.distanceTo(best.position)?pico:best,null);let target;if(carried?.userData.stolenFrom===rival)target=player.position;else if(nearest)target=nearest.position;else target=new THREE.Vector3(rival.home.x+Math.sin(time*.0007+rival.phase)*5,0,rival.home.z-4+Math.cos(time*.0009+rival.phase)*3);const delta=target.clone().sub(rival.bot.position);delta.y=0;const distance=delta.length();if(distance>.1){delta.normalize();const chase=carried?.userData.stolenFrom===rival;const speed=(chase?7.4:2.15)*dt;rival.bot.position.addScaledVector(delta,Math.min(speed,distance));rival.bot.rotation.y=Math.atan2(delta.x,delta.z);rival.bot.position.y=Math.abs(Math.sin(time*.01+rival.phase))*.06}if(nearest&&rival.bot.position.distanceTo(nearest.position)<1.55){const type=nearest.userData.type,mutation=nearest.userData.mutation;scene.remove(nearest);wildPicos.splice(wildPicos.indexOf(nearest),1);aiCollect(rival,type,mutation)}if(carried?.userData.stolenFrom===rival&&rival.bot.position.distanceTo(player.position)<1.5){const type={...carried.userData.type};if(carried.userData.mutation)type.storedMutation=carried.userData.mutation;scene.remove(carried);carried=null;rival.stock.push(type);refreshRivalDisplay(rival);toast(`${rival.name} caught you and took the Pico back!`)}if(!carried&&rival.stock.length&&rival.stealCooldown<=0&&player.position.distanceTo(rival.home)<3.7)stealFrom(rival);if(rival.display){rival.display.position.y=1.05+Math.sin(time*.003+rival.phase)*.12;rival.display.rotation.y+=dt*.5}}
}
const POWERS=[['Speed Burst','speed','#ffe45e'],['Bubble Shield','shield','#63ddff'],['Ice Freeze','freeze','#a9eaff'],['Pico Shockwave','shockwave','#ff7ec3'],['Shadow Cloak','cloak','#a987ff']];
function picoPower(type){const power=POWERS[type.id%POWERS.length];return {name:power[0],kind:power[1],color:power[2]}}
function activatePower(){if(!playing||!carried){toast('Carry a Pico to use its superpower!');return}if(worldTime<powerReadyAt){toast(`Power recharging: ${Math.ceil((powerReadyAt-worldTime)/1000)}s`);return}const power=picoPower(carried.userData.type),tier=rank[carried.userData.type.rarity],duration=(2.8+tier*.65)*1000;powerEffect={...power,until:worldTime+duration};powerReadyAt=worldTime+7000-Math.min(tier*450,2200);player.userData.aura.material.color.set(power.color);player.userData.aura.visible=true;if(power.kind==='shockwave'){for(const rival of aiBases){const push=rival.bot.position.clone().sub(player.position);push.y=0;if(push.length()<12){push.normalize();rival.bot.position.addScaledVector(push,7+tier)}}}toast(`${carried.userData.type.name} Pico used ${power.name}!`)}
function updatePower(time){worldTime=time;if(powerEffect&&time>=powerEffect.until){powerEffect=null;player.userData.aura.visible=false}if(powerEffect){player.userData.aura.rotation.z+=.08;const pulse=1+Math.sin(time*.012)*.15;player.userData.aura.scale.setScalar(pulse)}if(!carried){powerEffect=null;player.userData.aura.visible=false;powerValue.textContent='Find a Pico';mutationValue.textContent='Normal';return}mutationValue.textContent=carried.userData.mutation?`${carried.userData.mutation.name} x${carried.userData.mutation.multiplier}`:'Normal';const power=picoPower(carried.userData.type),remaining=Math.max(0,powerReadyAt-time);powerValue.textContent=powerEffect?`${power.name} ACTIVE`:remaining?`${power.name} ${Math.ceil(remaining/1000)}s`:`${power.name} [E]`}
function pick(){let n=Math.random()*weights.reduce((a,b)=>a+b),tier=0;for(;tier<weights.length;tier++){n-=weights[tier];if(n<=0)break}const pool=TYPES.filter(t=>rank[t.rarity]===tier);return pool[Math.floor(Math.random()*pool.length)]}
function spawn(){if(wildPicos.length>=10)return;const type=pick(),pico=makePico(type),a=Math.random()*Math.PI*2,r=8+Math.random()*16;pico.position.set(Math.cos(a)*r,0,Math.sin(a)*r-2);pico.userData.phase=Math.random()*10;let mutation=null;if(Math.random()<.28){const roll=Math.random(),index=roll<.42?0:roll<.7?1:roll<.86?2:roll<.94?3:roll<.97?4:roll<.99?5:6;mutation=MUTATIONS[index];mutatePico(pico,mutation,false)}wildPicos.push(pico);scene.add(pico);toast(mutation?.name==='Gem'?`NEW MUTATION ALERT! GEM ${type.name.toUpperCase()} PICO! Sparkly crystal trait · x${mutation.multiplier}`:mutation?.name==='Void'?`NEW MUTATION ALERT! VOID ${type.name.toUpperCase()} PICO! Cosmic shadow trait · x${mutation.multiplier}`:mutation?`${mutation.name} ${type.name} Pico spawned! Worth x${mutation.multiplier}`:`${type.rarity} Pico spawned! ${wildPicos.length} now roaming.`);}
function toast(s){document.querySelector('#toast').textContent=s}
function save(){localStorage.setItem('stealAPico',JSON.stringify(state));drawBook();hud()}
function hud(){const total=Object.values(state.caught).reduce((a,b)=>a+b,0);score.textContent=total;coins.textContent=state.coins;const got=TYPES.filter(t=>state.caught[t.name]).sort((a,b)=>rank[b.rarity]-rank[a.rarity])[0];best.textContent=got?got.rarity:'None'}
function drawBook(){const found=TYPES.filter(t=>state.caught[t.name]).length,mutationTotal=Object.values(state.mutations).reduce((a,b)=>a+(Number(b)||0),0),traits={Gold:'Shiny golden trait',Diamond:'Bright blue diamond trait',Yummi:'Sweet pink trait',Jhonso:'Wild green-orange trait',Void:'Cosmic shadow trait',Cyber:'Neon cyber trait',Gem:'Sparkling white crystal trait'};bookProgress.textContent=`${found} / ${TYPES.length} discovered · ${mutationTotal} mutated Picos stored`;picoGridElement.innerHTML=TYPES.map(t=>`<article class="entry ${state.caught[t.name]?'':'locked'}" style="--c:${t.color}"><div class="blob"></div><b>${state.caught[t.name]?t.name:'???'} Pico</b><small>${t.rarity}</small><span>${state.caught[t.name]||0} collected · ${values[rank[t.rarity]]} coins</span></article>`).join('');mutationGridElement.innerHTML=MUTATIONS.map(m=>{const count=Number(state.mutations[m.name])||0,name=m.name.toLowerCase();return `<article class="mutation-entry ${count?'':'empty'} ${name}" data-mutation="${m.name}" role="button" tabindex="0" style="--mutation:${m.color};--accent:${m.accent||m.color}"><div class="mutation-portrait"><div class="mutation-pico"><i></i><i></i><i></i></div></div><b>${m.name} Pico</b><small>${traits[m.name]} · x${m.multiplier}</small><strong>${count}</strong><span>collected · click to open</span></article>`}).join('')}
function openMutationBook(name){const mutation=MUTATIONS.find(m=>m.name===name);if(!mutation)return;const collected=state.mutationPicos[name]||{},knownTotal=Object.values(collected).reduce((a,b)=>a+(Number(b)||0),0),savedTotal=Number(state.mutations[name])||0,olderTotal=Math.max(0,savedTotal-knownTotal),styleName=name.toLowerCase();mutationDetailTitle.textContent=`${name} Pico Book`;mutationDetailTitle.style.color=mutation.color;mutationDetailSummary.textContent=`${savedTotal} ${name} Pico${savedTotal===1?'':'s'} stored`;const olderCard=olderTotal?`<article class="legacy-mutation mutation-entry ${styleName}" style="--mutation:${mutation.color};--accent:${mutation.accent||mutation.color}"><div class="mutation-portrait"><div class="mutation-pico"><i></i><i></i><i></i></div></div><b>${name} Pico</b><strong>${olderTotal}</strong><span>stored before Pico-name tracking</span></article>`:'';const picoCards=TYPES.map(t=>{const count=Number(collected[t.name])||0;return `<article class="entry mutation-detail-card ${count?'mutation-known':''}" style="--c:${t.color};--mutation:${mutation.color};--accent:${mutation.accent||mutation.color}"><div class="mutation-mini-pico ${styleName}"><i></i><i></i><i></i></div><b>${t.name} Pico</b><small>${t.rarity}</small><span>${count} ${name} collected</span></article>`}).join('');mutationPicoGrid.innerHTML=olderCard+picoCards;book.classList.add('detail-open');book.scrollTop=0}
function capture(pico){if(carried)return;carried=pico;wildPicos.splice(wildPicos.indexOf(pico),1);carried.scale.set(.55,.55,.55);toast(`You got ${carried.userData.type.name} Pico! Take it to base!`)}
function bank(){const t=carried.userData.type,m=carried.userData.mutation,multiplier=m?.multiplier||1,reward=values[rank[t.rarity]]*multiplier;state.caught[t.name]=(state.caught[t.name]||0)+1;state.coins+=reward;if(m){state.mutations[m.name]=(state.mutations[m.name]||0)+1;state.mutationPicos[m.name]??={};state.mutationPicos[m.name][t.name]=(state.mutationPicos[m.name][t.name]||0)+1}scene.remove(carried);carried=null;toast(`${m?m.name+' ':''}${t.name} Pico stored! +${reward} coins`);save()}
function update(dt,time){if(!playing)return;updatePower(time);let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dz=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0);const l=Math.hypot(dx,dz)||1,moving=!!(dx||dz),boost=powerEffect?.kind==='speed'?1.75:1,speed=(keys.Shift?10:6)*boost,s=speed*dt;player.position.x+=dx/l*s;player.position.z+=dz/l*s;player.position.x=Math.max(-25,Math.min(25,player.position.x));player.position.z=Math.max(-25,Math.min(25,player.position.z));if(moving){player.rotation.y=Math.atan2(dx,dz);const swing=Math.sin(time*.012*(keys.Shift?1.4:1));player.userData.limbs[0].rotation.x=swing*.65;player.userData.limbs[1].rotation.x=-swing*.65;player.userData.limbs[2].rotation.x=-swing*.55;player.userData.limbs[3].rotation.x=swing*.55;player.position.y=Math.abs(Math.sin(time*.012))*0.08}else{player.userData.limbs.forEach(limb=>limb.rotation.x*=.82);player.position.y*=.8}const guardBlocked=['shield','freeze','cloak'].includes(powerEffect?.kind);if(!guardBlocked)updateRivals(dt,time);for(const pico of [...wildPicos]){pico.rotation.y+=dt*.45;pico.position.y=Math.sin(time*.003+pico.userData.phase)*.16;const pulse=1+Math.sin(time*.006+pico.userData.phase)*.025;pico.scale.setScalar(pulse);if(!carried&&player.position.distanceTo(pico.position)<1.9)capture(pico)}if(carried){carried.position.set(player.position.x,4+Math.sin(time*.006)*.15,player.position.z);carried.rotation.y+=dt*2;if(player.position.distanceTo(base.position)<5.4)bank()}spawnTimer-=dt;if(spawnTimer<=0){spawn();spawnTimer=4.5}const camDistance=keys.Shift?15.5:14;camera.position.lerp(new THREE.Vector3(player.position.x+camDistance*.52,10.5,player.position.z+camDistance),.045);camera.lookAt(player.position.x,1.25,player.position.z);const near=aiBases.find(r=>r.stock.length&&player.position.distanceTo(r.home)<6);prompt.textContent=carried?'RETURN HOME · PRESS E FOR PICO POWER!':near?`${near.name.toUpperCase()} BASE · RUN INTO THE VAULT TO STEAL`:`${wildPicos.length} WILD PICO${wildPicos.length===1?'':'S'} ROAMING`}
function loop(t){const dt=Math.min((t-last)/1000,.05);last=t;update(dt,t);for(const pico of wildPicos)updateGemSparkles(pico,t);updateGemSparkles(carried,t);for(const rival of aiBases)updateGemSparkles(rival.display,t);renderer.render(scene,camera);requestAnimationFrame(loop)}
addEventListener('keydown',e=>{keys[e.key]=true;if((e.key==='e'||e.key==='E'||e.code==='Space')&&!e.repeat){activatePower();e.preventDefault()}});addEventListener('keyup',e=>keys[e.key]=false);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
document.querySelectorAll('[data-k]').forEach(b=>{for(const ev of ['pointerdown','pointerup','pointercancel','pointerleave'])b.addEventListener(ev,e=>{keys[b.dataset.k]=ev==='pointerdown';e.preventDefault()})});sprint.onpointerdown=()=>keys.Shift=true;sprint.onpointerup=()=>keys.Shift=false;powerButton.onclick=activatePower;
mutationGridElement.onclick=e=>{const card=e.target.closest('[data-mutation]');if(card)openMutationBook(card.dataset.mutation)};mutationGridElement.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.mutation){e.preventDefault();openMutationBook(e.target.dataset.mutation)}};backToBook.onclick=()=>{book.classList.remove('detail-open');book.scrollTop=0};bookBtn.onclick=()=>{drawBook();book.classList.remove('detail-open');book.scrollTop=0;book.classList.add('open')};closeBook.onclick=()=>{book.classList.remove('open','detail-open')};play.onclick=()=>{start.classList.add('hide');playing=true;spawnTimer=.5;toast('Keep watching—some wild Picos spawn with rare mutations!')};createRivals();hud();drawBook();camera.position.set(10,13,33);requestAnimationFrame(loop);
